//
//  VenuesPresenter.swift
//  Qorum
//
//  Created by Vadym Riznychok on 9/25/17.
//  Copyright (c) 2017 Bizico. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol VenuesPresentationLogic {
    
    
    /// Presents current state
    ///
    /// - Parameter response: state model
    func present(response: Venues.Response)
}

class VenuesPresenter {
    weak var viewController: VenuesDisplayLogic?
}

// MARK: - VenuesPresentationLogic
extension VenuesPresenter: VenuesPresentationLogic {
    
    func present(response: Venues.Response) {
        viewController?.display(viewModel: response)
    }
    
}
