//
//  VenuesModels.swift
//  Qorum
//
//  Created by Vadym Riznychok on 9/25/17.
//  Copyright (c) 2017 Bizico. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

struct Venues {
    
    enum Request {
        
        /// if venues update requested
        case venues
        
        /// if selected market changed
        case presentMainOverlayIfNeeded
        
        /// if last checkin requested
        case lastCheckins
        
        /// if checkin with free Uber ride requested
        case checkinsWithFreeRide
    }
    
    enum Response {
        
        /// if main overlay updated
        case mainOverlay
        
        /// if venues loaded
        case venues([Venue])
        
        /// opens Venues
        case openVenues
        
        /// to open Profile Screen
        case openProfile
        
        /// to Login
        case quitGuestMode
        
        /// if last Checkin loaded
        case lastCheckinsLoaded
        
        /// to venue review
        case review
    }
    
    typealias ViewModel = Response
    
}

