//
//  VenueReviewWorker.swift
//  Qorum
//
//  Created by Stanislav on 10.12.2017.
//  Copyright (c) 2017 Bizico. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

class VenueReviewWorker {
    
    /// Submits the review to Qorum server.
    ///
    /// - Parameters:
    ///   - checkin: The checkin to leave review to.
    ///   - completion: The completion handler closure.
    func leaveReview(checkin: Checkin,
                     completion: @escaping APIHandler<()>) {
        let user = User.stored
        if user.isGuest {
            completion(.error("Can't leave review in Guest mode!"))
            return
        }
        let request = VenuesRequest(target: .leaveReview(userId: user.userId,
                                                         checkinId: checkin.checkin_id,
                                                         rating: checkin.rating!,
                                                         numDrinks: checkin.num_drinks ?? 0,
                                                         feedback: checkin.feedback ?? ""))
        request.perform { response in
            switch response.result {
            case .value(_):
                completion(.success)
            case let .error(error):
                completion(.error(error))
            }
        }
    }
    
    /// Tracks the review via analytics (Mixpanel).
    ///
    /// - Parameter checkin: The checkin to leave review to.
    func trackReview(of checkin: Checkin) {
        let minutes: Double
        if let checkoutDate = checkin.checkout_time {
            let seconds = checkoutDate.timeIntervalSince(checkin.created)
            minutes = Time(seconds, .seconds)[in: .minutes]
        } else {
            minutes = 0
        }
        let ratingString: String
        if let rating = checkin.rating {
            ratingString = rating >= 1 ? "Thumbs Up" : "Thumbs Down"
        } else {
            ratingString = ""
        }
        AnalyticsService.shared.track(event: MixpanelEvents.submitVenueReview.rawValue,
                                      properties: ["Venue": checkin.venue?.name ?? "",
                                                   "Market": checkin.venue?.market?.name ?? "",
                                                   "Neighborhood": checkin.venue?.neighborhood ?? "",
                                                   "Time at Venue": minutes,
                                                   "Rating": ratingString])
    }
    
}

