//
//  VenueReviewRouter.swift
//  Qorum
//
//  Created by Stanislav on 10.12.2017.
//  Copyright (c) 2017 Bizico. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol VenueReviewRoutingLogic {
    func routeBack()
}

protocol VenueReviewDataPassing {
    var dataStore: VenueReviewDataStore? { get set }
}

class VenueReviewRouter: NSObject, VenueReviewDataPassing {
    weak var viewController: VenueReviewViewController?
    var dataStore: VenueReviewDataStore?
}

// MARK: - VenueReviewRoutingLogic
extension VenueReviewRouter: VenueReviewRoutingLogic {
    
    func routeBack() {
        viewController?.dismiss(animated: true, completion: nil)
    }
    
}

