//
//  BeaconsOnboardingModels.swift
//  Qorum
//
//  Created by Vadym Riznychok on 6/8/18.
//  Copyright (c) 2018 Bizico. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum BeaconsOnboarding {
    // MARK: Use cases
  
    enum Something {
        struct Request {
        }
        
        struct Response {
        }
    
        struct ViewModel {
        }
    }
}
