//
//  BeaconsOnboardingRouter.swift
//  Qorum
//
//  Created by Vadym Riznychok on 6/8/18.
//  Copyright (c) 2018 Bizico. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol BeaconsOnboardingRoutingLogic {
    func routeToBARVC()
    func dismiss()
}

protocol BeaconsOnboardingDataPassing {
    var dataStore: BeaconsOnboardingDataStore? { get }
}

class BeaconsOnboardingRouter: NSObject, BeaconsOnboardingRoutingLogic, BeaconsOnboardingDataPassing {
    weak var locationController: BeaconsOnboardingViewController?
    weak var refreshController: BeaconsOnboardingBARCheckViewController?
    var dataStore: BeaconsOnboardingDataStore?
  
    // MARK: Routing
    
    /// Opens Manual Beacons setup screen 
    func routeToBARVC() {
        let destinationVC = BeaconsOnboardingBARCheckViewController.fromStoryboard
        navigateToBAR(source: locationController!, destination: destinationVC)
    }
    
    func dismiss() {
        if let venuesVC = refreshController?.navigationController?.find(VenuesViewController.self) {
            refreshController?.navigationController?.popToViewController(venuesVC, animated: true)
        }
        
    }
    
    func navigateToBAR(source: BeaconsOnboardingViewController,
                       destination: BeaconsOnboardingBARCheckViewController) {
        source.navigationController?.pushViewController(destination, animated: true)
    }
}
