//
//  EmailInputModels.swift
//  Qorum
//
//  Created by Stanislav on 10.04.2018.
//  Copyright (c) 2018 Bizico. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

struct EmailInput {
    
    struct Request {
        
        /// email string
        let email: String
    }
    
    enum Response {
        
        /// invalid email warning
        case invalidEmail
        
        /// common error warning
        case error(Error)
        
        /// 
        case email(String)
        case success
    }
    
    enum ViewModel {
        
        /// shows warning
        case warning(String)
        
        /// shows email
        case email(String)
        
        /// shows close button
        case mayClose
    }
    
}
