//
//  EmailInputWorker.swift
//  Qorum
//
//  Created by Stanislav on 10.04.2018.
//  Copyright (c) 2018 Bizico. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class EmailInputWorker {
    
    private(set) lazy var editProfileWorker = EditProfileWorker()
    
    /// Validates given email string
    ///
    /// - Parameters:
    ///   - email: email to validate
    ///   - user: current user
    /// - Returns: result model
    func validate(email: String,
                  for user: User) -> APIResult<Bool> {
        guard !user.isGuest else {
            return .error("Can't verify email for the guest user")
        }
        guard email != (user.email ?? "") || !user.isEmailVerified else {
            return .error("PLEASE ENTER A DIFFERENT EMAIL ADDRESS")
        }
        return .value(email.isValidEmail)
    }
    
    /// Submits user's email for validation
    ///
    /// - Parameters:
    ///   - email: email string
    ///   - user: current user
    ///   - completion: completion block
    func submit(email: String,
                for user: User,
                completion: @escaping (EmailInput.Response)->()) {
        editProfileWorker.updateUser(id: user.userId, parameters: ["email": email]) { result in
            switch result {
            case .value:
                completion(.success)
            case let .error(error):
                completion(.error(error))
            }
        }
    }
    
}

