//
//  LoadingInteractor.swift
//  Qorum
//
//  Created by Vadym Riznychok on 9/25/17.
//  Copyright (c) 2017 Bizico. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

protocol LoadingBusinessLogic {
    func checkState()
    func cityBackgroundUpdated()
}

protocol LoadingDataStore { }

class LoadingInteractor: LoadingDataStore {
    
    var presenter: LoadingPresentationLogic?
    var updateTimer: Timer?
    let updateTimeout: TimeInterval = 10

    private(set) lazy var worker = LoadingWorker()
    
    /** flag indicating if background is updated */
    private(set) var backgroundUpdated = false
    
    /** checks to see if the selected market background image is updated.
        If background image was updated or Qorum Configuration App allows Quick launch launches app.
        If not asks presenter to update corresponding background image.
     */
    func readyToUpdateBackground() {
        if backgroundUpdated || AppConfig.quickLaunch {
            readyToGo()
            return
        } 
        presenter?.present(blocker: .needsUpdateBackground)
    }
    
    /** launches the app */
    func readyToGo() {
        presenter?.mayGo(to: worker.preferredDestination)
    }
    
}

// MARK: - LoadingBusinessLogic
extension LoadingInteractor: LoadingBusinessLogic {
    
    /**
     * Checks the state before app launch.
     */
    func checkState() {
        switch worker.state {
        case .blocked(let blocker):
            presenter?.present(blocker: blocker)
        case .needsCheckNotificationsAccess:
            worker.notificationsAccessState { [weak self] accessIsGranted in
                guard accessIsGranted else {
                    self?.presenter?.present(blocker: .needsNotificationAccess)
                    return
                }
                self?.readyToUpdateBackground()
            }
        case .goodToGo:
            readyToUpdateBackground()
        }
    }
    
    /// Called when background gets updated
    func cityBackgroundUpdated() {
        backgroundUpdated = true
        readyToGo()
    }
    
}
