//
//  LoadingModels.swift
//  Qorum
//
//  Created by Vadym Riznychok on 9/25/17.
//  Copyright (c) 2017 Bizico. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

enum Loading {
    
    /** Possible responses */
    enum Response {
        
        /** is blocked */
        case blocked(Blocker)
        
        /** is push notifications permissions should be checked */
        case needsCheckNotificationsAccess
        
        /** is ready to launch */
        case goodToGo
        
        /** block reasons */
        enum Blocker {
            
            /** user's age is unknown */
            case shouldDisplayAgeGating
            
            /** tutorial unshowed */
            case shouldDisplayOnboarding
            
            /** is locations permissions request is unshowed */
            case needsLocationAccess
            
            case needsMarketsLoaded
            case needsCloserLocation
            
            /** is push notifications permissions request is unshowed*/
            case needsNotificationAccess
            
            /** market's background image is not updated */
            case needsUpdateBackground
        }
        
    }
    
    /** Possible routes */
    enum Route {
        
        /** to user's age confirmation */
        case ageGating
        
        /** to the tutorial */
        case onboarding

        /** to the permissions */
        case access
        
        case locationBlock
        
        case destination(Destination)
        
        enum Destination {
            
            /** to log in */
            case auth
            
            /** to the list of venues */
            case venues
        }
        
    }
    
}
