//
//  OnboardingWorker.swift
//  Qorum
//
//  Created by Vadym Riznychok on 9/26/17.
//  Copyright (c) 2017 Bizico. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class OnboardingWorker {
    
}
