//
//  LocationBlockPresenter.swift
//  Qorum
//
//  Created by Stanislav on 31.01.2018.
//  Copyright (c) 2018 Bizico. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol LocationBlockPresentationLogic {
    func present(response: LocationBlock.Response)
    func showLoader(message: String)
    func hideLoader()
}

class LocationBlockPresenter {
    weak var viewController: LocationBlockDisplayLogic?
}

// MARK: - LocationBlockPresentationLogic
extension LocationBlockPresenter: LocationBlockPresentationLogic {
    
    func present(response: LocationBlock.Response) {
        let viewModel: LocationBlock.ViewModel
        switch response {
        case .invalidEmail:
            viewModel = .warning("Please check your email")
        case .invalidLocation:
            viewModel = .warning("Please check your location permissions in Settings")
        case .error(let error):
            viewModel = .warning(error.message)
        case .success:
            viewModel = .success
        }
        viewController?.display(viewModel: viewModel)
    }
    
    func showLoader(message: String) {
        viewController?.showLoader(message)
    }
    
    func hideLoader() {
        viewController?.hideLoader()
    }

}

