//
//  MapInteractor.swift
//  Qorum
//
//  Created by Dima Tsurkan on 11/10/17.
//  Copyright (c) 2017 Bizico. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MapBusinessLogic {
    func fetchMapItems()
    func openProfile()
}

protocol MapDataStore {
    var venues: [Venue] { get }
}

class MapInteractor: MapDataStore {
    
    var presenter: MapPresentationLogic?
    private(set) lazy var worker = MapWorker()
    var venues: [Venue] {
        return CityManager.shared.allVenues
    }
    var user: User { return User.stored }
}

// MARK: - MapBusinessLogic
extension MapInteractor: MapBusinessLogic {
    
    func fetchMapItems() {
        let items = worker.mapItems(for: venues)
        self.presenter?.present(mapItems: items)
    }
    
    /// Opens user profile
    func openProfile() {
        if user.isGuest {
            presenter?.quitGuestMode()
        } else {
            presenter?.openProfile()
        }
    }
    
}
