//
//  MapModels.swift
//  Qorum
//
//  Created by Dima Tsurkan on 11/10/17.
//  Copyright (c) 2017 Bizico. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

struct Map {
    
    enum ViewModel {
        
        /// update map items state
        case mapItems([VenueMapItem])
        
        /// open user profile state
        case openProfile
        
        /// open login screen state
        case quitGuestMode
    }
    
}
