//
//  MapPresenter.swift
//  Qorum
//
//  Created by Dima Tsurkan on 11/10/17.
//  Copyright (c) 2017 Bizico. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MapPresentationLogic {
    func present(mapItems: [VenueMapItem])
    func openProfile()
    func quitGuestMode()
}

class MapPresenter {
    weak var viewController: MapDisplayLogic?
}

// MARK: - MapPresentationLogic
extension MapPresenter: MapPresentationLogic {
    
    func present(mapItems: [VenueMapItem]) {
        viewController?.display(viewModel: .mapItems(mapItems))
    }
    
    func openProfile() {
        viewController?.display(viewModel: .openProfile)
    }
    
    func quitGuestMode() {
        viewController?.display(viewModel: .quitGuestMode)
    }
    
}
