//
//  MapWorker.swift
//  Qorum
//
//  Created by Dima Tsurkan on 11/10/17.
//  Copyright (c) 2017 Bizico. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class MapWorker {
    
    /// Creates map marker models from venue list
    ///
    /// - Parameter venues: venues to present on map
    /// - Returns: venues models suitable to present on map
    func mapItems(for venues: [Venue]) -> [VenueMapItem] {
        let locations: [String: [Venue]] = venues.reduce(into: [:]) { (locations, venue) in
            let location = "\(venue.coordinate.latitude) \(venue.coordinate.longitude)"
            locations[location, default: []].append(venue)
        }
        
        var items: [VenueMapItem] = []
        for (_, locationVenues) in locations {
            let lastIndex = Double(locationVenues.count-1)
            for (index, venue) in locationVenues.enumerated() {
                let indexOffset = Double(index) / lastIndex
                let latOffset: Double = lastIndex < 1 ? 0 : indexOffset * 0.00004
                let pos = CLLocationCoordinate2D(latitude: venue.coordinate.latitude + latOffset,
                                                 longitude: venue.coordinate.longitude)
                
                let item = VenueMapItem(position: pos, venue: venue)
                items.append(item)
            }
        }
        return items
    }
    
}
