//
//  PaymentsRouter.swift
//  Qorum
//
//  Created by Dima Tsurkan on 11/27/17.
//  Copyright (c) 2017 Bizico. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol PaymentsRoutingLogic {
    
    /// Opens Add New Card Screen
    func routeToAddNewPaymentMethod()
    
    /// Shows previous screen
    func routeBack()
}

protocol PaymentsDataPassing {
    var dataStore: PaymentsDataStore? { get }
}

class PaymentsRouter: NSObject, PaymentsDataPassing {
    weak var viewController: PaymentsViewController?
    var dataStore: PaymentsDataStore?
}

extension PaymentsRouter: PaymentsRoutingLogic {
    
    func routeToAddNewPaymentMethod() {
        let destinationVC = AddNewPaymentViewController.fromStoryboard
        viewController?.show(destinationVC, sender: nil)
    }
    
    func routeBack() {
        viewController?.navigationController?.popViewController(animated: true)
    }
    
}
