//
//  PaymentsModels.swift
//  Qorum
//
//  Created by Dima Tsurkan on 11/27/17.
//  Copyright (c) 2017 Bizico. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

struct Payments {
    
    enum Request {
        
        /// if credit cards list update requested
        case fetchCards
        
        /// if default payment method update requested
        case setDefaultPayment(Payment)
        
        /// if delete card requested
        case deleteCard(CreditCard)
    }
    
    typealias Response = APIResult<[CreditCard]>
    
    struct ViewModel {
        let cards: [CreditCard]
    }
    
    typealias LoadingState = EditProfile.UpdateState
    
    enum Payment {
        
        /// Apple Pay payment method
        case applePay
        
        /// Payment with Credit card 
        case card(CreditCard)
        
        var stringValue: String {
            switch self {
            case .applePay: return "ApplePay"
            case .card: return "CreditCard"
            }
        }
        
    }
    
}
