//
//  InviteWorker.swift
//  Qorum
//
//  Created by Stanislav on 29.11.2017.
//  Copyright (c) 2017 Bizico. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import Mixpanel

class InviteWorker {
    
    var user: User {
        return User.stored
    }
    
    /// Submits Invite Event to the Mixpanel
    ///
    /// - Parameters:
    ///   - type: event type
    ///   - status: event status
    ///   - appearanceType: appearanceType
    func trackInvite(for type: UIActivityType, status: Invite.Result.Status, appearanceType: String) {
        var typeStr = ""
        switch type {
        case .postToFacebook:
            typeStr = "Facebook"
        case .postToTwitter:
            typeStr = "Twitter"
        case .mail:
            typeStr = "Email"
        case .message:
            typeStr = "SMS"
        default:
            typeStr = "Other"
        }
        AnalyticsService.shared.track(event: MixpanelEvents.inviteAFriend.rawValue, properties: ["Invite Option": typeStr,
                                                                                                 "Invite Status" : status.rawValue,
                                                                                                 "Invite Screen Accessed By": appearanceType])
    }
    
}
