//
//  InviteModels.swift
//  Qorum
//
//  Created by Stanislav on 29.11.2017.
//  Copyright (c) 2017 Bizico. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

struct Invite {
    
    enum Request {
        
        /// if invite via Facebook requested
        case facebook(from: InviteViewController)
        
        /// if invite via Twitter requested
        case twitter(from: InviteViewController)
        
        /// if invite via text link requested
        case other(from: InviteViewController)
        
        /// if invite via Email requested
        case email(from: InviteViewController)
        
        /// if invite via SMS requested
        case sms(from: InviteViewController)
    }
    
    struct Response {
        let user: User
    }
    
    enum ViewModel {
        
        /// if blocked - phone and email verification needed
        case needsVerifyPhoneAndEmail
        
        /// if blocked - phone verification needed
        case needsVerifyPhone
        
        /// if blocked - email verification needed
        case needsVerifyEmail
        
        /// if profile unlocked
        case verified(items: [TableItem])
    }
    
    struct TableItem {
        let name: String
        let count: Int
    }
    
    struct Result {
        
        enum Status: String {
            case cancelled = "cancelled"
            case failed = "failed"
            case succeed = "succeed"
        }
        
        struct Response {
            var source: UIActivityType
            var status: Status
        }
        
        struct ViewModel {
            var title: String
            var message: String
        }
    }
    
}
