//
//  NumberInputModels.swift
//  Qorum
//
//  Created by Stanislav on 05.04.2018.
//  Copyright (c) 2018 Bizico. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

struct NumberInput {
    
    struct Request {
        
        /// phone number
        let number: String
    }
    
    enum Response {
        
        /// phone number
        case phone(String)
        
        /// phone number is invalid
        case invalidNumber
        
        /// error received
        case error(Error)
        
        /// verification is successful
        case success
    }
    
    enum ViewModel {
        
        /// phone number to display
        case phone(String)
        
        /// custom warning to display
        case warning(String)
        
        /// allows to verify received a code
        case mayVerifyCode
    }
    
    struct Phone {
        let countryCode: String
        let phoneNumber: String
    }
    
}



