//
//  NumberInputPresenter.swift
//  Qorum
//
//  Created by Stanislav on 05.04.2018.
//  Copyright (c) 2018 Bizico. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol NumberInputPresentationLogic: class {
    
    /// Presents current state
    ///
    /// - Parameter response: response model with current state
    func present(response: NumberInput.Response)
    
    /// Shows loader with custom message
    ///
    /// - Parameter message: message to show
    func showLoader(message: String)

    /// Hides loader
    func hideLoader()
}

class NumberInputPresenter {
    weak var viewController: NumberInputDisplayLogic?
}

// MARK: - NumberInputPresentationLogic
extension NumberInputPresenter: NumberInputPresentationLogic {
    
    func present(response: NumberInput.Response) {
        let viewModel: NumberInput.ViewModel
        switch response {
        case .phone(let phone):
            viewModel = .phone(phone)
        case .invalidNumber:
            viewModel = .warning("PLEASE ENTER A VALID PHONE NUMBER")
        case .error(let error):
            viewModel = .warning(error.message)
        case .success:
            viewModel = .mayVerifyCode
        }
        viewController?.display(viewModel: viewModel)
    }
    
    func showLoader(message: String) {
        viewController?.showLoader(message)
    }
    
    func hideLoader() {
        viewController?.hideLoader()
    }
    
}

