//
//  SettingsRouter.swift
//  Qorum
//
//  Created by Stanislav on 02.05.2018.
//  Copyright (c) 2018 Bizico. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol SettingsRoutingLogic {
     func routeBack()
}

protocol SettingsDataPassing {
    var dataStore: SettingsDataStore? { get }
}

class SettingsRouter: NSObject, SettingsDataPassing {
    
    weak var viewController: SettingsViewController?
    var dataStore: SettingsDataStore?
    
}

// MARK: - SettingsRoutingLogic
extension SettingsRouter: SettingsRoutingLogic {
    
    /* Opens previous screen */
    func routeBack() {
        viewController?.navigationController?.popViewController(animated: true)
    }
    
}

