//
//  CodeInputRouter.swift
//  Qorum
//
//  Created by Stanislav on 09.04.2018.
//  Copyright (c) 2018 Bizico. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol CodeInputRoutingLogic {
    
    /// Returns to previous screen
    func routeBack()
    
    /// Opens email verification screen
    func routeToEmailVerification()
    
    /// Closes screen
    func routeClose()
}

protocol CodeInputDataPassing {
    var dataStore: CodeInputDataStore? { get }
}

class CodeInputRouter: NSObject, CodeInputDataPassing {
    
    weak var viewController: CodeInputViewController?
    var dataStore: CodeInputDataStore?
    
    // MARK: Navigation
    
    //func navigateToSomewhere(source: CodeInputViewController, destination: SomewhereViewController) {
    //    source.show(destination, sender: nil)
    //}
    
    // MARK: Passing data
    
    //func passDataToSomewhere(source: CodeInputDataStore, destination: inout SomewhereDataStore) {
    //    destination.name = source.name
    //}
    
}

// MARK: - CodeInputRoutingLogic
extension CodeInputRouter: CodeInputRoutingLogic {
    
    func routeBack() {
        viewController?.navigationController?.popViewController(animated: true)
    }
    
    func routeToEmailVerification() {
        let destinationVC = EmailInputViewController.fromStoryboard
        viewController?.navigationController?.pushViewController(destinationVC, animated: true)
    }
    
    func routeClose() {
        viewController?.navigationController?.dismiss(animated: true, completion: nil)
    }
    
}

