//
//  SearchPresenter.swift
//  Qorum
//
//  Created by Stanislav on 31.01.2018.
//  Copyright (c) 2018 Bizico. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SearchPresentationLogic {
    
}

class SearchPresenter {
    weak var viewController: SearchDisplayLogic?
}

// MARK: - SearchPresentationLogic
extension SearchPresenter: SearchPresentationLogic {
    
}

