//
//  SearchRouter.swift
//  Qorum
//
//  Created by Stanislav on 31.01.2018.
//  Copyright (c) 2018 Bizico. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol SearchRoutingLogic {
    
    /// Opens previous screen
    func routeBack()
    
    /// Opens profile
    func routeToProfile()
}

protocol SearchDataPassing {
    var dataStore: SearchDataStore? { get }
}

class SearchRouter: NSObject, SearchDataPassing {
    
    weak var viewController: SearchViewController?
    var dataStore: SearchDataStore?
    
}

// MARK: - SearchRoutingLogic
extension SearchRouter: SearchRoutingLogic {
    
    func routeBack() {
        viewController?.dismiss(animated: true, completion: nil)
    }
    
    func routeToProfile() {
        if let presentingNavigationVC = viewController?.presentingViewController as? UINavigationController {
            let profileVC = ProfileViewController.fromStoryboard
            presentingNavigationVC.pushViewController(profileVC, animated: false)
        }
        viewController?.dismiss(animated: true, completion: nil)
    }
    
}

