//
//  UberOrderModels.swift
//  Qorum
//
//  Created by Vadym Riznychok on 12/4/17.
//  Copyright (c) 2017 Bizico. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum UberOrder {
    // MARK: Use cases
  
    enum Something {
        struct Request {
        }
        
        struct Response {
        }
    
        struct ViewModel {
        }
    }
    
    enum ApplyPromo {
        
        enum Response {
            case success
            case alreadyApplied
            case invalidPromo
            case error(Error)
        }
        
    }
    
}
