//
//  UberOrderPresenter.swift
//  Qorum
//
//  Created by Vadym Riznychok on 12/4/17.
//  Copyright (c) 2017 Bizico. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol UberOrderPresentationLogic {
    func presentUberAuthError(_ error: NSError)
    func presentAuthorize(_ token: String)
}

class UberOrderPresenter: UberOrderPresentationLogic {
    weak var viewController: UberOrderDisplayLogic?
  
    // MARK:
    
    func presentUberAuthError(_ error: NSError) {
        viewController?.showAuthError(error)
    }
    
    func presentAuthorize(_ token: String) {
        viewController?.authorizeReturn(token)
    }
}
